<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>86JPGM</AssemblyName>
    <RootNamespace>Jp86.GmClient</RootNamespace>
    <ApplicationIcon>GM.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="GM.ico" />
    <ProjectReference Include="..\PvfLib\PvfLib.csproj" />
  </ItemGroup>
</Project>
